/** @type {import('./_types').Chapter[]} */
export const CHAPTERS = [
  {
    id: "how-elections-work",
    number: "01",
    title: "How Indian Elections Work",
    subtitle: "The world's largest democracy, explained",
    readTime: "5 min read",
    icon: "Landmark",
    accent: "#F97316",
    sections: [
      {
        id: "intro",
        type: "prose",
        title: "One billion eligible voters. One independent commission.",
        body: "India runs the world's largest democratic exercise. Every 5 years, the **Election Commission of India (ECI)** — an independent constitutional body — organises elections to the Lok Sabha (Parliament's lower house) and all State Assemblies.\n\nThe ECI operates without government interference. It can transfer officers, suspend officials, and even override state governments during election periods. Its neutrality is the bedrock of Indian democracy.",
      },
      {
        id: "structure",
        type: "prose",
        title: "Two elections you need to know",
        body: "**Lok Sabha (General Elections)**\n- 543 constituencies across India\n- Held every 5 years\n- You vote for your local MP (Member of Parliament)\n- The party/alliance with majority forms the government\n- Prime Minister is chosen by the winning coalition\n\n**Vidhan Sabha (State Elections)**\n- Each state has its own assembly\n- Held separately from Lok Sabha (except sometimes simultaneously)\n- You vote for your local MLA (Member of Legislative Assembly)\n- Chief Minister is chosen by the winning coalition",
      },
      {
        id: "constituencies",
        type: "callout",
        calloutType: "fact",
        body: "India has **543 Lok Sabha constituencies** and over **4,000 Vidhan Sabha constituencies**. Each constituency elects one representative by a simple first-past-the-post system — the candidate with the most votes wins, even without a majority.",
      },
      {
        id: "phases",
        type: "prose",
        title: "Why elections happen in phases",
        body: "India is vast. A single-day election is impossible — the entire security apparatus (police, paramilitary) must be deployed phase by phase.\n\nThe 2024 Lok Sabha election ran across **7 phases over 6 weeks**. Each phase covers certain states. Counting happens on a single day after all phases are done.\n\nThis phased system ensures:\n- Security forces can move between regions\n- The ECI can monitor all booths simultaneously\n- Remote and difficult terrain gets adequate time",
      },
      {
        id: "quiz-1",
        type: "quiz",
        question: {
          question: "How many Lok Sabha seats does India have?",
          options: ["343", "443", "543", "643"],
          correct: 2,
          explanation: "India has 543 Lok Sabha constituencies. 272 seats are needed for a majority to form the government.",
        },
      },
    ],
  },
  {
    id: "voter-registration",
    number: "02",
    title: "Voter Registration & the Electoral Roll",
    subtitle: "How your name gets on the list — and stays there",
    readTime: "6 min read",
    icon: "ClipboardList",
    accent: "#3B6FEB",
    sections: [
      {
        id: "what-is-roll",
        type: "prose",
        title: "The Electoral Roll — India's master voter list",
        body: "The Electoral Roll (also called the Voter List) is the official database of all eligible voters in each constituency. It's maintained by the **Electoral Registration Officer (ERO)** of each constituency — typically a senior district official.\n\nEvery year, the ECI conducts a **Special Summary Revision** to update the roll — adding new voters, correcting errors, and removing those who have died or moved. This usually happens between October and January.",
      },
      {
        id: "qualifying-dates",
        type: "prose",
        title: "Four qualifying dates per year",
        body: "Since 2022, India has four qualifying dates per year for voter registration:\n\n- **1 January**\n- **1 April**\n- **1 July**\n- **1 October**\n\nYou must be 18 on or before any of these dates to register for that cycle. This replaced the old system where only 1 January was the qualifying date — meaning someone born on 2 January had to wait nearly a year.",
      },
      {
        id: "forms",
        type: "timeline",
        title: "The right form for every situation",
        items: [
          { year: "Form 6", event: "New voter registration", detail: "First-time voters or those moving to a new constituency" },
          { year: "Form 7", event: "Deletion request", detail: "Report a deceased voter or a name that should not be on the roll" },
          { year: "Form 8", event: "Correction / address update", detail: "Fix spelling, address, photo, or personal details within the same constituency" },
          { year: "Form 6B", event: "Overseas voter", detail: "Indian citizens living abroad who wish to vote in person" },
        ],
      },
      {
        id: "blo",
        type: "callout",
        calloutType: "tip",
        body: "**Your BLO (Booth Level Officer)** is the most important person in your voter registration journey. They verify your address in person, approve your application, and can help if your name was wrongly deleted. Find your BLO via the Voter Helpline app or by calling **1950**.",
      },
      {
        id: "epic",
        type: "prose",
        title: "Your EPIC — the Voter ID Card",
        body: "**EPIC** stands for **Elector's Photo Identity Card**. It's issued by the ECI and serves as both your proof of voter registration and a valid government photo ID accepted across India.\n\nYou can download your **e-EPIC** (digital PDF version) instantly from voters.eci.gov.in. It's legally equivalent to the physical card and accepted at polling booths.",
      },
      {
        id: "quiz-2",
        type: "quiz",
        question: {
          question: "What form do you fill if you want to update your address within the same constituency?",
          options: ["Form 6", "Form 7", "Form 8", "Form 6B"],
          correct: 2,
          explanation: "Form 8 handles corrections within the same constituency — including address changes, name spelling fixes, and photo replacement.",
        },
      },
    ],
  },
  {
    id: "election-day",
    number: "03",
    title: "Election Day — What Actually Happens",
    subtitle: "Inside the booth, from queue to EVM",
    readTime: "7 min read",
    icon: "Vote",
    accent: "#15803D",
    sections: [
      {
        id: "notification",
        type: "prose",
        title: "From notification to polling day",
        body: "An election begins when the **President (or Governor, for states)** issues the Notification of Election on the ECI's recommendation. From that moment:\n\n- **Day 0:** Notification issued — nomination process opens\n- **Days 1–14:** Candidates file nominations\n- **Day 14:** Scrutiny of nominations\n- **Day 16:** Last day to withdraw\n- **Campaign period:** Usually 2–3 weeks\n- **48 hours before polling:** Campaign silence begins (no rallies, no ads)\n- **Polling Day:** Booths open 7 AM – 6 PM",
      },
      {
        id: "model-code",
        type: "callout",
        calloutType: "fact",
        body: "The **Model Code of Conduct (MCC)** kicks in the moment elections are announced. It prohibits the government from announcing new schemes, transferring key officials, or using government machinery for campaign purposes. The ECI enforces it strictly — and has removed chief ministers from official residences for MCC violations.",
      },
      {
        id: "at-booth",
        type: "prose",
        title: "At the polling booth — exactly what happens",
        body: "**1. Queue:** Arrive at your assigned booth. Senior citizens and PwD voters get priority entry.\n\n**2. Identity check (1st Officer):** Shows your name in the electoral roll + checks your photo ID. 12 IDs accepted including Aadhaar, PAN, Passport, Driving Licence.\n\n**3. Ink (2nd Officer):** Indelible ink applied to your **left index finger**. This is your physical proof of voting — it lasts 2–3 weeks.\n\n**4. Slip + entry (3rd Officer):** You receive a numbered slip and enter the voting compartment.\n\n**5. Vote:** Press the button next to your candidate on the EVM. Confirm on the VVPAT.",
      },
      {
        id: "multiple-id",
        type: "callout",
        calloutType: "tip",
        body: "If you don't have your EPIC card, **any one of these 12 documents works:** Aadhaar, PAN, Passport, Driving Licence, Service ID (government employees), Passbook with photo (bank/post office), MNREGA job card, Health insurance smart card, Pension document, MP/MLA/MLC official identity card, Unique Disability ID. No document = no vote.",
      },
      {
        id: "quiz-3",
        type: "quiz",
        question: {
          question: "On which finger is indelible ink applied during voting?",
          options: ["Right index finger", "Left thumb", "Left index finger", "Right thumb"],
          correct: 2,
          explanation: "Indelible ink is applied on the left index finger. It contains silver nitrate and lasts 2–3 weeks, preventing double voting.",
        },
      },
    ],
  },
  {
    id: "evm-vvpat",
    number: "04",
    title: "The EVM & VVPAT — How Your Vote is Recorded",
    subtitle: "The technology behind India's tamper-resistant elections",
    readTime: "5 min read",
    icon: "Cpu",
    accent: "#7C3AED",
    sections: [
      {
        id: "what-is-evm",
        type: "prose",
        title: "What is an EVM?",
        body: "**EVM stands for Electronic Voting Machine.** It consists of two linked units:\n\n- **Ballot Unit (BU):** The voter-facing panel with candidate names and blue buttons\n- **Control Unit (CU):** Operated by the Presiding Officer — activates the BU for each voter\n\nThe EVM is a standalone device. It has **no internet connection, no wireless chip, no Bluetooth**. It cannot be hacked remotely because there's nothing to hack into — it's completely offline.",
      },
      {
        id: "evm-security",
        type: "prose",
        title: "Why tamper-resistance is built in",
        body: "EVMs are manufactured by only two government companies: **BEL (Bharat Electronics Limited)** and **ECIL (Electronics Corporation of India Limited)**.\n\n- The software is burned into one-time programmable chips — it cannot be rewritten\n- The hardware is custom-designed, not standard PC components\n- Machines are **First Level Checked (FLC)** in the presence of party representatives before every election\n- After polling, EVMs are stored in strongrooms guarded by CRPF, with seals checked by all candidates",
      },
      {
        id: "vvpat",
        type: "prose",
        title: "VVPAT — Your physical verification",
        body: "**VVPAT (Voter Verifiable Paper Audit Trail)** is the paper receipt machine attached to every EVM.\n\nWhen you press a button on the Ballot Unit:\n1. A paper slip prints inside the VVPAT box showing the **candidate's name, serial number, and party symbol**\n2. You see it through a transparent window for **7 seconds**\n3. The slip drops automatically into a sealed compartment\n4. You cannot take it home — it's for verification only\n\nThe VVPAT paper record can be counted if there's a dispute — this is how physical verification works.",
      },
      {
        id: "evm-simulator",
        type: "evm",
      },
      {
        id: "quiz-4",
        type: "quiz",
        question: {
          question: "How long is the VVPAT slip visible to the voter?",
          options: ["3 seconds", "5 seconds", "7 seconds", "10 seconds"],
          correct: 2,
          explanation: "The VVPAT slip is visible for exactly 7 seconds through the transparent window. If you don't see it or it doesn't match, call the Presiding Officer immediately.",
        },
      },
    ],
  },
  {
    id: "results-government",
    number: "05",
    title: "From Results to Government",
    subtitle: "How votes become power",
    readTime: "4 min read",
    icon: "BarChart3",
    accent: "#F59E0B",
    sections: [
      {
        id: "counting",
        type: "prose",
        title: "Counting day — the biggest number game",
        body: "All EVMs from all phases are counted on a **single day** after polling is complete. Counting happens at designated Counting Centres, constituency by constituency.\n\nThe process:\n1. Postal ballots (military, overseas, seniors) are counted first\n2. EVM Control Units are unsealed in the presence of candidates' agents\n3. Results are tallied round by round on a **Round-by-Round basis**\n4. Returning Officer declares the result for that constituency\n5. National tallies accumulate throughout the day\n\nResults for all 543 seats typically come in within **10–12 hours** of counting start.",
      },
      {
        id: "government-formation",
        type: "prose",
        title: "How a government is formed",
        body: "**272 seats** = majority in a 543-seat Lok Sabha.\n\n- If a single party wins 272+, they form the government alone\n- If no single party wins, coalition negotiations begin\n- The President invites the **largest coalition** to prove majority\n- The coalition leader becomes **Prime Minister**\n- PM recommends **Cabinet ministers** to the President\n- Cabinet must prove majority through a **floor test** if challenged\n\nThe **Speaker** of the Lok Sabha is elected by MPs and manages parliamentary proceedings.",
      },
      {
        id: "opposition",
        type: "callout",
        calloutType: "fact",
        body: "The **Leader of Opposition** is a constitutionally recognised position — but only if the opposition party has at least **10% of Lok Sabha seats (55 seats)**. If no party qualifies, there is officially no Leader of Opposition, which affects oversight committees.",
      },
      {
        id: "timeline",
        type: "timeline",
        title: "From election to government — typical timeline",
        items: [
          { year: "Counting day", event: "Results declared", detail: "All 543 seats called within 10-12 hours" },
          { year: "Day 1–3", event: "Coalition negotiations", detail: "Parties meet, alliance confirmations, horse-trading" },
          { year: "Day 3–7", event: "President invites", detail: "President invites coalition leader to form government" },
          { year: "Day 7–10", event: "Swearing in", detail: "PM and Cabinet sworn in at Rashtrapati Bhavan" },
          { year: "Day 10–30", event: "Floor test", detail: "New government proves majority in Lok Sabha" },
        ],
      },
      {
        id: "quiz-5",
        type: "quiz",
        question: {
          question: "How many Lok Sabha seats are needed for a majority government?",
          options: ["200", "251", "272", "300"],
          correct: 2,
          explanation: "272 out of 543 seats gives a simple majority in the Lok Sabha. Without this, coalition negotiations begin.",
        },
      },
    ],
  },
  {
    id: "rights-and-resources",
    number: "06",
    title: "Your Rights & Resources",
    subtitle: "What you're entitled to — and where to go for help",
    readTime: "4 min read",
    icon: "Shield",
    accent: "#EC4899",
    sections: [
      {
        id: "rights",
        type: "prose",
        title: "Your fundamental voting rights",
        body: "Every registered voter in India has these rights:\n\n**At the booth:**\n- Priority entry if you are a senior citizen, pregnant, or PwD\n- Assistance from a companion of your choice inside the booth (if physically unable)\n- Right to see the VVPAT slip\n- Right to cast a **Tendered Ballot** if your vote is already recorded (someone voted in your name)\n\n**After voting:**\n- Right to complain about booth malpractice to the Sector Officer or ECI directly\n- Right to demand re-poll if there's serious irregularity\n- Right to NOTA (None of the Above) — a legitimate ballot option",
      },
      {
        id: "nota",
        type: "callout",
        calloutType: "fact",
        body: "**NOTA (None of the Above)** appears as the last option on every EVM. It was introduced in 2013 after a Supreme Court ruling. NOTA votes are counted but do not affect the result — the candidate with the most votes still wins, even if NOTA gets more. NOTA is a protest vote, not a veto.",
      },
      {
        id: "resources",
        type: "timeline",
        title: "Your official help resources",
        items: [
          { year: "1950", event: "Voter Helpline", detail: "24/7 helpline for all electoral queries — multilingual" },
          { year: "voters.eci.gov.in", event: "National Voter Services Portal", detail: "Forms 6, 7, 8 — apply, track, download e-EPIC" },
          { year: "electoralsearch.eci.gov.in", event: "Electoral Search", detail: "Check if your name is on the voter list" },
          { year: "Voter Helpline App", event: "Official ECI Mobile App", detail: "Find your booth, BLO details, apply for corrections" },
          { year: "cVIGIL", event: "Violation Reporting App", detail: "Report MCC violations, bribery, or booth malpractice with a photo/video" },
        ],
      },
      {
        id: "complaints",
        type: "prose",
        title: "What to do if something goes wrong",
        body: "**Before election day:**\n- Name missing → File Form 6 immediately, contact your BLO\n- Wrong details → File Form 8, attach supporting documents\n\n**On election day:**\n- Booth malpractice → Call 1950 immediately, ask for Sector Officer\n- Someone already voted in your name → Request a Tendered Ballot\n- Bribed or threatened → Use the cVIGIL app (geotagged evidence)\n\n**After election day:**\n- EVM concerns → File a petition in the High Court within 45 days of results\n- Candidate misconduct → File a complaint with the Returning Officer",
      },
      {
        id: "quiz-6",
        type: "quiz",
        question: {
          question: "What is NOTA on the EVM?",
          options: [
            "A way to reject all candidates and trigger a re-election",
            "A protest vote that is counted but doesn't affect the winner",
            "Only available in national elections, not state elections",
            "Introduced in 2019",
          ],
          correct: 1,
          explanation: "NOTA (None of the Above) is a valid ballot option introduced in 2013. NOTA votes are tallied but the candidate with the most votes still wins — NOTA is not a veto.",
        },
      },
    ],
  },
];

export const CHAPTER_MAP = Object.fromEntries(CHAPTERS.map((c) => [c.id, c]));
